/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "auyxjyvtliqhelpgqdvf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1eXhqeXZ0bGlxaGVscGdxZHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Nzk4MTQsImV4cCI6MjA3MzI1NTgxNH0.1_lg78HHpYI2VG-YGYhl24D8g_Dx_RIn-goSjxL-jO0"