import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"
import ClientLayoutProviders from "./ClientLayoutProviders";
const micrenFont = localFont({
  src: "./fonts/micrenc.ttf",
  variable: "--font-micrenc",
  display: "swap",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CheckPrint Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${micrenFont.variable} antialiased`}
      >
        <ClientLayoutProviders>
          {children}
        </ClientLayoutProviders>
        
      </body>
    </html>
  );
}
